services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations && \
                      python manage.py migrate && \
                      python manage.py collectstatic --noinput && \
                      python manage.py runserver 0.0.0.0:8000" 
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - backend_static:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app  
      - /app/node_modules
    environment:
      - NODE_ENV=development 
    ports:
      - 5173:5173
    depends_on:
      - backend

  postgres:
    image: postgres:17.4
    env_file: ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  redis_data:
  backend_static:
