# Generated by Django 5.2 on 2025-05-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='number_of_rooms',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
