# Generated by Django 5.2 on 2025-05-05 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_alter_apartment_number_of_rooms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Apartment', 'verbose_name_plural': 'Apartments'},
        ),
        migrations.RenameIndex(
            model_name='apartment',
            new_name='price_availability_idx',
            old_name='apartments__price_e867f9_idx',
        ),
        migrations.RenameIndex(
            model_name='apartment',
            new_name='slug_idx',
            old_name='apartments__slug_a3f4f9_idx',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='availability',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Availability'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='number_of_rooms',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Number of rooms'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=8, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='square',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Square'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
